### ISSUE TITLE
cropToSelector does not crop page regions correctly (chrome; not tested on firefox)

### ISSUE THREAD

**Issue by rickschubert** [newsuk/AyeSpy#181]
Example config:

```
{
    "gridUrl": "http://localhost:4444/wd/hub",
    "baseline": "./baseline",
    "latest": "./latest",
    "generatedDiffs": "./generatedDiffs",
    "report": "./reports",
    "scenarios": [
        {
            "url": "https://www.google.com/",
            "label": "homepage-chrome",
            "cropToSelector": "#body",
            "viewports": [
                {
                    "height": 1080,
                    "width": 1400,
                    "label": "standard"
                },
                {
                    "height": 1080,
                    "width": 1920,
                    "label": "wide"
                },
                {
                    "height": 1080,
                    "width": 600,
                    "label": "mobile"
                }
            ],
            "wait": 0
        }
    ]
}
```

Actual screenshot taken: 
![image](https://user-images.githubusercontent.com/25436915/56816642-d9ec1e00-683b-11e9-9094-3e6db2df5d5a.png)

Aye-spy version: 4.3.0
Chrome version: Version 74.0.3729.108 (Official Build) (64-bit)
ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72)

This happens across many different websites, not just google - from my perception it seems like `cropToSelector` never works correctly.

**Comment by lukasr22** [comment]
Hello @rickschubert ,
Thank You for using AyeSpy. 
I was retesting same scenario with your config file and standard and wide image was all right. Mobile wasnt but because even google page on browser didnt restyle if window is smaller for this example is 600px. Image Attached 
![image](https://user-images.githubusercontent.com/43343000/56891952-0a1f0100-6a76-11e9-9128-06af8f4851a8.png)

Better option for mobile is using mobileEmulator option: https://github.com/newsuk/AyeSpy#mobile-emulator
What version of Grid and chrome in grid do you using? 
I was tested it wit AyeSpy 4.3.0
Selenium grid version: 3.14.0 also chrome in grid have same version.
Do you have more examples where cropToSelector doesn't work correctly?
Thanks.

**Comment by mdcruz** [comment]
Closing this issue as there hasn't been any activity
