### ISSUE TITLE
Limit the number of parallel scenarios being run

### ISSUE THREAD

**Issue by mdcruz** [newsuk/AyeSpy#94]
Nice to have if there is a feature where we can limit the number of parallel scenarios we run. Something like `ayespy snap --scenarios=10`

**Comment by shendriksen** [comment]
Would be nice to call it ```--concurrency``` if we implement this feature.

**Comment by kaliabadi** [comment]
I think this is actually a bug with the way we interact with the grid rather than an enhancement but needs some investigation to prove this. 

Should be a simple fix regardless as we can just split the promises into arrays of a fixed size (from your concurrency field or a parameter from your grid) and do promise all on that. @shendriksen @L0wry

**Comment by L0wry** [comment]
#108

**Comment by kaliabadi** [comment]
merged
